spring:
  profiles:
    active: "local"
  datasource:
    driverClassName: org.h2.Driver
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PW:password}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  servlet:
    context-path: /axie/api/v1

url:
  frontend:
    firebase: ${URL_FRONTEND_FIREBASE:}
    
# jwt

jwt:
  expiration: 1200000
  secret: ${JWT_SECRET:any_secret}
    
# actuator
management:
  endpoint:
    health:
      show-details: always
  web:
    exposure:
      include: "*"

---

spring:
  profiles: prod
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/axie}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PW:pass}
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  servlet:
    context-path: /axie/api/v1
    
logging:
  level:
    .: INFO
    org.springframework: INFO
    
# app
url:
  frontend:
    firebase: ${URL_FRONTEND_FIREBASE:}
    
# jwt

jwt:
  expiration: 1200000
  secret: ${JWT_SECRET:any_secret}
    
# actuator
management:
  endpoint:
    health:
      show-details: always
  web:
    exposure:
      include: "*"

